core/forms/create.py
from flask_wtf import FlaskForm as form
from wtforms import StringField, SubmitField, HiddenField
from wtforms.validators import DataRequired


class CreateForm(form):
    title = StringField('title', validators=[DataRequired()])
    category = StringField('category', validators=[DataRequired()])
    description = HiddenField("description")
    folder = HiddenField('folder')
    date = HiddenField('date')
    updated = HiddenField('updated')
    publish = SubmitField('Publish')
    draft = SubmitField('Draft')

core/views.py
import re
import os

from urllib.parse import urlencode, parse_qs
from functools import wraps
from datetime import datetime

import markdown2 as md2
from flask import (
    Blueprint,
    render_template,
    request,
    jsonify,
    send_from_directory,
    redirect,
    url_for)

from werkzeug.utils import secure_filename

from core.forms import CreateForm, FolderForm
from core.script import initialize, create_blobs, create_git_tree, \
    create_git_commit, update_commit, get_contents, \
    get_content_from_folder, decode_content, update_file, create_element_tree, \
    create_git_blob, create_input_git_tree
from core.utils import allowed_file, create_static_page, move_images, clear_temp_static, \
    get_file_contents, get_article_data, UPLOAD_FOLDER, \
    PAGES, make_dir, post_call, get_session_token, get_app_config, get_post_folder, \
    get_content_type, github_remove_images

blueprint = Blueprint('core', '__name__')

# constant start
github_identity_url = 'https://github.com/login/oauth/authorize'
github_access_token_url = 'https://github.com/login/oauth/access_token'

if 'DYNO' in os.environ:
    root_url = 'https://gatsby-ssg.herokuapp.com/'
else:
    root_url = 'http://localhost:5000'

authorize_url = 'http://localhost:5000/authorize'
# constant end


def github_upload_images(new_images, upload_folder, path):
    """
     new_images(list): new images list to upload
     upload_folder(string): image path
     path(string): github path to upload
     repo(object): github repo object
    """
    # create new element list and update the folder with added image
    if new_images:
        auth = initialize()
        if not auth[0]:
            return

        init = auth[1]
        branch = init.get('branch')
        master_ref = init.get('master_ref')
        repo = init.get('repo')
        tree = init.get('tree')
        parent = repo.get_git_commit(branch.commit.sha)

        # create blob for each image

        blobs = create_blobs(upload_folder, repo, upload_list=new_images)
        # create element tree
        element_tree = create_element_tree(blobs, path)
        # create git tree
        git_tree = create_git_tree(repo, element_tree, tree)
        # update the head commit

        git_commit = create_git_commit(repo, 'new image added to {}'.format(path), git_tree, parent)
        update_commit(master_ref, git_commit.sha)

    return


def login_required(function=None, redirect_url=''):
    def actual_decorator(func):
        @wraps(func)
        def _wrapped_view(*args, **kwargs):

            github_auth = get_session_token()
            if github_auth:
                if redirect_url:
                    return redirect(redirect_url)
                else:
                    return func(*args, **kwargs)
            else:
                return redirect(url_for('core.login', redirect=redirect_url))

        return _wrapped_view

    if function:
        return actual_decorator(function)
    return actual_decorator


@blueprint.context_processor
def authenticate_check():
    authenticated = get_session_token()
    return dict(is_autheticated=True if authenticated else False)


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    client_id = os.getenv('GITHUB_CLIENTID')
    params = {'client_id': client_id, 'scope': "user,repo"}
    url = github_identity_url + '?' + urlencode(params)
    return redirect(url)


@blueprint.route('/logout')
def logout():
    config = get_app_config()
    config['GITHUB_ACCESSTOKEN'] = ''
    config['IS_LOGOUT'] = True
    return redirect(root_url)


@blueprint.route('/authorize', methods=['GET', 'POST'])
def github_authorize():
    config = get_app_config()
    code = request.args.get('code')
    client_id = os.getenv('GITHUB_CLIENTID')
    client_secret = os.getenv('GITHUB_CLIENTSECRET')
    data = {'client_id': client_id, 'client_secret': client_secret, 'code': code}

    # github_auth = get_session_token()
    response = post_call(github_access_token_url, data=data)
    reponse_data = parse_qs(response.content)

    for k, v in reponse_data.items():
        if len(v) == 1:
            data[k] = v[0]
        token = reponse_data.get(b'access_token', None)
        if token is not None:
            token = token[0].decode('ascii')
            config['GITHUB_ACCESSTOKEN'] = token
            return redirect(root_url)
        else:
            return redirect('/configure')


@blueprint.route('/', methods=['GET', 'POST'])
def index():
    """
    Initialize the github folders.
    """
    auth = initialize()
    if auth and auth[0]:
        init = auth[1]
        repo = init.get('repo')

        # get the posts location in github
        posts_folder = get_post_folder()
        if posts_folder:
            folders = get_contents(repo, posts_folder)
        else:
            return redirect('/configure')

        contents = get_content_from_folder(repo, folders)
        display_pages = {}

        for key, value in contents.items():
            files = value['files']
            for file in files:
                temp = {}
                if not allowed_file(file.path):
                    text = decode_content(file.content, True)
                    display_content = get_file_contents(text)[0]
                    temp = get_article_data(display_content)

                    if temp.get('title'):
                        temp['path'] = value['path']
                        display_pages[temp['title']] = temp
                    else:
                        print(key, value)

        return render_template('index.html', pages=display_pages)
    elif not auth:
        return render_template('index.html')
    else:
        return redirect(url_for('core.' + auth[1]))


@blueprint.route('/drafts', methods=['GET', 'POST'])
def draft():
    auth = initialize()
    if auth and auth[0]:
        init = auth[1]
        repo = init.get('repo')

        # get the posts location in github
        posts_folder = get_post_folder(draft=True)
        if posts_folder:
            folders = get_contents(repo, posts_folder)
        else:
            return redirect('/configure')
        if folders:
            contents = get_content_from_folder(repo, folders)
            display_pages = {}

            for key, value in contents.items():
                files = value['files']
                for file in files:
                    temp = {}
                    if not allowed_file(file.path):
                        text = decode_content(file.content, True)
                        display_content = get_file_contents(text)[0]
                        temp = get_article_data(display_content)

                        if temp.get('title'):
                            temp['path'] = value['path']
                            display_pages[temp['title']] = temp
                        else:
                            print(key, value)

            return render_template('index.html', pages=display_pages)
        else:
            return render_template('index.html', pages={})
    elif not auth:
        return render_template('index.html')
    else:
        return redirect(url_for('core.' + auth[1]))


@blueprint.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = CreateForm()
    # before starting remove the previous stuffs
    clear_temp_static()
    if form.validate_on_submit():
        # breakpoint()
        dir_1 = datetime.now().strftime("%d-%b-%Y")
        dir_2 = form.data['title']
        dir_name = dir_1.replace('/', '-') + '--' + dir_2.replace(' ', '-')[:20]
        dir_path = PAGES + '/' + dir_name
        make_dir(dir_path)
        file_path = dir_path + '/' + 'index.md'
        description = form.data['description']
        draft = form.data['draft']
        images_path = re.findall('/temp/.*?\.[jpg|jpeg|png|gif]+', description)

        # TODO: remove the ne static path creation

        # move images to particular folder
        updated_description = re.sub('\(/temp/', '(./', description)
        create_static_page(file_path, dir_2, form.data['category'], updated_description)
        images_status = move_images(images_path, dir_path)

        if not images_status[0]:
            return render_template('create.html', form=form, error=True, status=images_status[1])

        # Push to git rep
        get_repo = initialize()

        if get_repo[0]:
            init = get_repo[1]
            repo = init.get('repo')
            branch = init.get('branch')
            tree = init.get('tree')
            master_ref = init.get('master_ref')

            # created blob
            blobs = create_blobs(dir_path, repo)

            # create element list
            git_dir = dir_path.split('/')[-1]

            posts_folder = get_post_folder(draft)
            if posts_folder:
                git_path = '{}{}'.format(posts_folder, git_dir)
            else:
                return redirect('/configure')

            # create Element Tree
            element_tree = create_element_tree(blobs, git_path)

            # create gittree
            if element_tree:
                git_tree = create_git_tree(repo, element_tree, tree)
                # create git commit
                parent = repo.get_git_commit(branch.commit.sha)
                git_commit = create_git_commit(repo, 'new post added in {}'.format(git_dir), git_tree, parent)
                # update the head commit
                update_commit(master_ref, git_commit.sha)

            # After the github upload remove the temp
            clear_temp_static(True)
            return redirect(root_url)
        else:
            return redirect(url_for('core.' + get_repo[1]))
    return render_template('create.html', form=form)


@blueprint.route('/editpage', methods=['GET', 'POST'])
@login_required
def edit_page():
    if request.method == 'GET':
        clear_temp_static(True)
        path = request.args.get('path', None)
        folder_path = path.split('/')[-1]
        if path:

core/templates/base.html
<!doctype html>
<html>
  <head>
      <title>{% block title %}{% endblock %}</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="stylesheet" href="/static/styles.css">
      <meta charset="utf-8">
      {% block head %}
		  {% endblock %}
  </head>
  <body>
        <div class="nav-container">
            <div class="box-1">
              {% if is_autheticated%}
                  <a href="/" id='homeurl'>Home</a>
                  <a href="/drafts">Drafts</a>
                  <a href="/create">Create New Blog</a>
                  <a href="/configure">Configure Github Folders</a>
               {%else%}
               <div></div>
               {% endif %}
            </div>

            <div class="box-2">
              {% if is_autheticated%}
                <a href="/logout">Logout</a>
              {% else %}
                <a href="/login">Login</a>
              {%endif%}
            </div>
        </div>
        <div class="error">
          <h4>{{error}}</h4>
        </div>
        <div class="content-container">
          {% if is_autheticated%}
          {% block content %}{% endblock %}
          {% block script %} {%endblock%}
          {%else%}
            <h3> Please login and <a href="/configure">configure github </a>repo details</h3>
          {%endif%}
        </div>
        <script>

          // const home_id = document.getElementById("homeurl")
          // home_id.href = window.location.host
        </script>
  </body>
</html>

core/templates/create.html
{% extends 'base.html'%}

{% block head %}
<script src="/static/highlight/highlight.js"></script>
<script src="/static/utils/turndown.js"></script>
<link href="/static/quill/quill.snow.css" rel="stylesheet">
<script src="/static/quill/quill.js"></script>
<script src="/static/utils/image-resize.js"></script>

{% endblock%}

{% block content %}
     <div class="flex-col">
         <div class="ls-content">
            <h4>
              Localstorage Content
            </h4>
              <button type="button" name="button" id='clear_local'>Clear</button>
            <ol id='posts'>

            </ol>
         </div>
          <form action="" id= 'createform' method="post">
            {%if error %}
               <h2 style="color:red">Reupload: <br/>{{status}}</h2>
            {% endif %}
          {{ form.hidden_tag() }}
          <label>
            Enter title
          </label>
          {{form.title}}
          <br/>
          <label>
            Enter category
          </label>
          {{form.category}}
          <br/>
          {{form.description}}
          <label>Enter content</label>
          <div id="editor"></div>
          <div class="buttons">
          {{form.publish}}
          {{form.draft}}
          </div>
          </form>
    </div>
{% endblock %}

{% block script %}
<script type="module">
  import LocalStorage from '/static/utils/localstorage.js'
  const store_access = new LocalStorage()

  // get the data for form
  document.getElementById('createform').addEventListener('submit', saveFormData)
  document.getElementById('clear_local').addEventListener('click', clearLocalStorage)

  let add_posts = document.getElementById('posts')

  function createLiNode(text){
    const liNode = document.createElement('li')
    liNode.textContent = text
    return liNode
  }
  function updatePosttoForm(){
    //clear current form

    form.reset()
    //get value from localStorage
    const key = this.parentNode.children[0].textContent
    let data = LocalStorage.getData(key)
    addToForm(data)
  }
  function addToForm(data){
    const keys= Object.keys(data)
    debugger;
    for (var key of keys){
      if (key === 'description'){
        quill.root.innerHTML = data[key]
      }
      document.getElementById(key).value = data[key]
    }
  }
  function createButton(buttontext, id){
    const button = document.createElement("button");
    button.innerHTML = buttontext;
    button.id = id
    return button
  }
  function createLiDiv(){
    const div = document.createElement('div');
    div.className = 'postli'
    return div
  }
  function saveFormData(){
    /***
     save data to LocalStorage and reterive later
    ***/
    const key = document.getElementById('title').value
    const form_data = {
      title: key,
      category: document.getElementById('category').value,
      description : quill.root.innerHTML
    }
    store_access.setData(key, form_data)
  }
  function clearLocalStorage(){
    LocalStorage.clearAll()
    add_posts.innerHTML = ''
  }
  function addPosts(posts){
    add_posts.innerHTML = ''
    for (let post in posts){
        const li = createLiNode(posts[post])
        li.id = post
        const button = createButton('Add', post)
        const node = createLiDiv()
        node.appendChild(li)
        node.appendChild(button)
        add_posts.appendChild(node)
    }
  }
  // get all contents from localStorage
  const posts =  LocalStorage.getAllContents()
  addPosts(posts)
  const buttons = document.querySelectorAll('.postli button')

  //apply onlclick to all button
  for(let button of buttons){
    button.addEventListener('click', updatePosttoForm)
  }
</script>
<script>

    var toolbarOptions = [
          ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
          ['blockquote', 'code-block'],
           ['link', 'image'],

          [{ 'header': 1 }, { 'header': 2 }],               // custom button values
          [{ 'list': 'ordered'}, { 'list': 'bullet' }],
          [{ 'script': 'sub'}, { 'script': 'super' }],      // superscript/subscript
          [{ 'indent': '-1'}, { 'indent': '+1' }],          // outdent/indent
          [{ 'direction': 'rtl' }],                         // text direction

          [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown
          [{ 'header': [1, 2, 3, 4, 5, 6, false] }],

          [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
          [{ 'font': [] }],
          [{ 'align': [] }],

          ['clean']                                         // remove formatting button
        ];
    let quill = new Quill('#editor', {
      theme: 'snow',
      modules: {
        syntax: true,
        toolbar:toolbarOptions,
        imageResize: {
           displaySize: true
         }
       },
    });

    var form  = document.getElementById('createform')

    const imageHandler = () => {
        const input = document.createElement('input');
        input.setAttribute('type', 'file');
        input.setAttribute('accept', 'image/*');
        input.click();
        input.onchange = async () => {
       const file = input.files[0];
       const formData = new FormData();

       formData.append('image', file);

       // Save current cursor state
       const range = quill.getSelection(true);

       // Insert temporary loading placeholder image
       quill.insertEmbed(range.index, 'image', `${ window.location.origin }/images/loaders/placeholder.gif`);

       // Move cursor to right side of image (easier to continue typing)
       quill.setSelection(range.index + 1);

       const res = await fetch('/uploads', {
         method: 'POST',
         body: formData
       })
       .then((response) => response.json())
       .catch((error) =>{
         return error
       }); // API post, returns image location as string e.g. 'http://www.example.com/images/foo.png'

       // Remove placeholder image
       quill.deleteText(range.index, 1);

       // Insert uploaded image
       quill.insertEmbed(range.index, 'image', res.data);
     }
    }
    const toolbar = quill.getModule('toolbar')
    toolbar.addHandler('image', imageHandler)

    let description = document.getElementById('description')

    form.addEventListener('submit', sendDescription)

    function sendDescription(){
          const description_data = quill.root.innerHTML
          description.value = description_data
          // html to markdown converter
          const ts = new TurndownService()
          ts.addRule('code', {
          filter: ['pre'],
          replacement: function (content, node, options) {
            // need to fix this currently replace all backslash
            // code block

            content = content.replace(/\\/g, '')
            return '```\n' + content + '```'
          }
          })

          ts.addRule('italicChange',{
            filter: ['em'],
            replacement: function (content) {
              return '*' + content + '*'
            }
          })
          ts.addRule('h1Change',{
            filter: ['h1'],
            replacement: function (content) {
              return '#' + content
            }
          })
          ts.addRule('h2Change',{
              filter: ['h2'],
              replacement: function (content) {
                return '##' + content
              }
           })
          ts.addRule('h3Change',{
               filter: ['h3'],
               replacement: function (content) {
                 return '###' + content
               }
          })
          ts.addRule('h4Change',{
               filter: ['h4'],
               replacement: function (content) {
                 return '####' + content
               }
          })
          ts.addRule('h5Change',{
               filter: ['h5'],
               replacement: function (content) {
                 return '#####' + content
               }
          })
          ts.addRule('h6Change',{
               filter: ['h6'],
               replacement: function (content) {
                 return '######' + content
               }
          })
          const description_md = ts.turndown(description_data)
          description.value = description_md
        }


</script>
<script type="text/javascript" src="/static/utils/quill_customize.js">

</script>
{% endblock %}

core/templates/edit.html
{% extends 'base.html'%}
{% block head %}

    <script src="/static/highlight/highlight.js"></script>
    <link href="/static/highlight/styles/codepen-embed.css" rel="stylesheet">
    <script src="/static/utils/turndown.js"></script>
    <link href="/static/quill/quill.snow.css" rel="stylesheet">
    <script src="/static/quill/quill.js"></script>
    <script src="/static/utils/image-resize.js"></script>
{% endblock%}

{% block content %}
   <div class="flex-col">
      <div class="ls-content">
         <h4>
           Localstorage Content
         </h4>
           <button type="button" name="button" id='clear_local'>Clear</button>
         <ol id='posts'>

         </ol>
      </div>
      <form action="" id = "editform" method="post" novalidate>
            {%if description%}
            <input type="hidden" name="path" id='path' value={{path}}>
            {{form.folder}}
            {{form.date}}
            {{form.updated}}
            <label>
              Enter title
            </label>
              {{form.title}}
                  <br/>
              <label>
                Enter Category
              </label>
              {{form.category}}
                  <br/>
              {{form.description}}
              <label>Enter content</label>
              <div id="editor"></div>
              <div class="buttons">
              {{form.publish}}
              {{form.draft}}
              </div>
            {%else%}
              <h3>No page to display</h3>
            {%endif%}

      </form>
    </div>

{% endblock %}

{% block script %}

<script type="module">
  //This script need to be moved to common folder
  import LocalStorage from '/static/utils/localstorage.js'
  const store_access = new LocalStorage()

  // get the data for form
  form.addEventListener('submit', saveFormData)
  document.getElementById('clear_local').addEventListener('click', clearLocalStorage)

  let add_posts = document.getElementById('posts')

  function createLiNode(text){
    const liNode = document.createElement('li')
    liNode.textContent = text
    return liNode
  }
  function updatePosttoForm(){
    //clear current form

    form.reset()
    //get value from localStorage
    const key = this.parentNode.children[0].textContent
    let data = LocalStorage.getData(key)
    addToForm(data)
  }
  function addToForm(data){
    const keys= Object.keys(data)
    for (var key of keys){
      if (key === 'description'){
        quill.root.innerHTML = data[key]
      }
      document.getElementById(key).value = data[key]
    }
  }
  function createButton(buttontext, id){
    const button = document.createElement("button");
    button.innerHTML = buttontext;
    button.id = id
    return button
  }
  function createLiDiv(){
    const div = document.createElement('div');
    div.className = 'postli'
    return div
  }
  function saveFormData(){
    /***
     save data to LocalStorage and reterive later
    ***/
    const key = document.getElementById('title').value
    const form_data = {
      title: key,
      category: document.getElementById('category').value,
      description : quill.root.innerHTML,
      path:document.getElementById('path').value,
      folder:document.getElementById('folder').value,
      date:document.getElementById('date').value,
      updated:document.getElementById('updated').value
    }
    store_access.setData(key, form_data)
  }
  function clearLocalStorage(){
    LocalStorage.clearAll()
    add_posts.innerHTML = ''
  }
  function addPosts(posts){
    add_posts.innerHTML = ''
    for (let post in posts){
        const li = createLiNode(posts[post])
        li.id = post
        const button = createButton('Add', post)
        const node = createLiDiv()
        node.appendChild(li)
        node.appendChild(button)
        add_posts.appendChild(node)
    }
  }
  // get all contents from localStorage
  const posts =  LocalStorage.getAllContents()
  addPosts(posts)
  const buttons = document.querySelectorAll('.postli button')

  //apply onlclick to all button
  for(let button of buttons){
    button.addEventListener('click', updatePosttoForm)
  }
</script>

<script>
    var form  = document.getElementById('editform')
    var toolbarOptions = [
        ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
        ['blockquote', 'code-block'],
         ['link', 'image'],

        [{ 'header': 1 }, { 'header': 2 }],               // custom button values
        [{ 'list': 'ordered'}, { 'list': 'bullet' }],
        [{ 'script': 'sub'}, { 'script': 'super' }],      // superscript/subscript
        [{ 'indent': '-1'}, { 'indent': '+1' }],          // outdent/indent
        [{ 'direction': 'rtl' }],                         // text direction

        [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown
        [{ 'header': [1, 2, 3, 4, 5, 6, false] }],

        [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
        [{ 'font': [] }],
        [{ 'align': [] }],

        ['clean']                                         // remove formatting button
    ];

    let quill = new Quill('#editor', {
      theme: 'snow',
      scrollingContainer: "#editor",
      modules: {
        syntax: true,
        toolbar:toolbarOptions,
        imageResize: {
           displaySize: true
         }
       },
    });

    const initial_description = {{ description | tojson}};

    quill.clipboard.dangerouslyPasteHTML(initial_description + "\n");

    const imageHandler = () => {
      const input = document.createElement('input');
      input.setAttribute('type', 'file');
      input.setAttribute('accept', 'image/*');
      input.click();
      input.onchange = async () => {
     const file = input.files[0];
     const formData = new FormData();

       formData.append('image', file);

       // Save current cursor state
       const range = quill.getSelection(true);

       // Insert temporary loading placeholder image
       quill.insertEmbed(range.index, 'image', `${ window.location.origin }/images/loaders/placeholder.gif`);

       // Move cursor to right side of image (easier to continue typing)
       quill.setSelection(range.index + 1);


       const res = await fetch('/uploads', {
         method: 'POST',
         body: formData
       })
       .then((response) => response.json())
       .catch((error) =>{
         return error
       }); // API post, returns image location as string e.g. 'http://www.example.com/images/foo.png'

       // Remove placeholder image
       quill.deleteText(range.index, 1);

       // Insert uploaded image
       quill.insertEmbed(range.index, 'image', res.data);
       }
      }

    const toolbar = quill.getModule('toolbar')
    toolbar.addHandler('image', imageHandler)

    form.addEventListener('submit', sendDescription)
    let description = document.getElementById('description')

    function sendDescription(){
    const description_data = quill.root.innerHTML
    description.value = description_data
    // html to markdown converter
    const ts = new TurndownService()
    ts.addRule('code', {
    filter: ['pre'],
    replacement: function (content) {
      content = content.replace(/\\/g, '')
      return '```\n' + content + '```'
      }
    })
    ts.addRule('italicChange',{
      filter: ['em'],
      replacement: function (content) {
        return '*' + content + '*'
      }
    })
    ts.addRule('h1Change',{
      filter: ['h1'],
      replacement: function (content) {
        return '#' + content
      }
    })
    ts.addRule('h2Change',{
        filter: ['h2'],
        replacement: function (content) {
          return '##' + content
        }
     })
    ts.addRule('h3Change',{
         filter: ['h3'],
         replacement: function (content) {
           return '###' + content
         }
    })
    ts.addRule('h4Change',{
         filter: ['h4'],
         replacement: function (content) {
           return '####' + content
         }
    })
    ts.addRule('h5Change',{
         filter: ['h5'],
         replacement: function (content) {
           return '#####' + content
         }
    })
    ts.addRule('h6Change',{
         filter: ['h6'],
         replacement: function (content) {
           return '######' + content
         }
    })
    const description_md = ts.turndown(description_data)
    description.value = description_md
  }
</script>
<script type="text/javascript" src="/static/utils/quill_customize.js">

</script>
{% endblock %}

core/templates/github_folder.html
{% extends 'base.html'%}

{% block content %}
  <div class="github-config-container">
      <div class="info">
        <h4 class="warning"> Note: </h4>
        <h2>Always enter the folder name with trailing slash not on prefix</h2>
        <h3>e.g., If folder post folder is conten/blog and draft folder is content/draft<h3>
          <p>
            <strong class="warning">content/blogs/</strong>

          </p>
          <strong class="warning">content/draft/</strong>

       </div>
      <form action="" method="post">
          <label>
            Enter Repo Name
          </label>
          {{form.repo}}
          <label>
            Enter Post Folder
          </label>
          {{form.posts_folder}}
          <label>
            Enter Draft Folder
          </label>
          {{form.drafts_folder}}
          {{form.submit}}
      </form>
  </div>
{% endblock %}

core/templates/index.html
{% extends 'base.html'%}

{% block content %}

<div class="homecontainer">
  {%if pages%}
    {%for key, value in pages.items()%}
      <h3>{{key}}</h3>
      <h6>Category: {{value['category']}}</h6>
      <a href="{{url_for('core.edit_page', path=value['path'])}}">Edit</a>
      <a href="">Delete</a>
      <hr>
   {%endfor%}
   {%else%}
     <h3>No contents.</h3>
   {%endif%}
</div>
{% endblock %}

core/templates/login.html
{% extends 'base.html'%}

{% block content %}
  <form action="" method="post">
    {{form.username}}
    {{form.redirect}}
    {{form.submit}}
  </form>
{% endblock %}

{% block script%}
   <script>
     const redirect_url = {{redirect_to | tojson }}
     const redirectId = document.getElementById('redirect')
     if (redirect){
       redirectId.value = redirect_url
     }
  </script>
{%endblock%}